theme: jekyll-theme-cayman
title: Welcome to the Andy's homepage!
# github:
  # repository_name: BeyondSword.github.io
  # repository_url: BeyondSword.github.io
  # repository: BeyondSword.github.io

# PAGES_REPO_NWO: aaa
repository: BeyondSword/BeyondSword.github.io
